// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bot/commands": {
            "get": {
                "description": "Get all Discord commands that the bot implements",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bot"
                ],
                "summary": "Get Bot Commands",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/discordgo.ApplicationCommand"
                            }
                        }
                    }
                }
            }
        },
        "/bot/info": {
            "get": {
                "description": "Get basic information about the bot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bot"
                ],
                "summary": "Get Bot Info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Info"
                        }
                    }
                }
            }
        },
        "/game/roomcode": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get the Among Us room code most recently reported by the capture client for a connect code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Get Room Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Connect Code",
                        "name": "connectCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RoomCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.HttpError"
                        }
                    }
                }
            }
        },
        "/game/state": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get the current state of a running game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Get Game State",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild ID",
                        "name": "guildID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Connect Code",
                        "name": "connectCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stored game state, using the bot's JSON representation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/guild/premium": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get the premium status for a given guild",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "guild"
                ],
                "summary": "Get Guild Premium",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild ID",
                        "name": "guildID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/premium.PremiumRecord"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.HttpError"
                        }
                    }
                }
            }
        },
        "/guild/settings": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get the settings for a given guild. Guilds that never changed a setting get the defaults.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "guild"
                ],
                "summary": "Get Guild Settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild ID",
                        "name": "guildID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/settings.GuildSettings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.HttpError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.HttpError"
                        }
                    }
                }
            }
        },
        "/open/link": {
            "get": {
                "description": "Return html that open AmongUsCapture",
                "produces": [
                    "text/html"
                ],
                "summary": "Get AmongUsCapture",
                "responses": {
                    "200": {
                        "description": "text/html",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.HttpError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "api.Info": {
            "type": "object",
            "properties": {
                "activeGames": {
                    "type": "integer"
                },
                "commit": {
                    "type": "string"
                },
                "totalGames": {
                    "type": "integer"
                },
                "totalGuilds": {
                    "type": "integer"
                },
                "totalUsers": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.RoomCodeResponse": {
            "type": "object",
            "properties": {
                "connectCode": {
                    "type": "string"
                },
                "roomCode": {
                    "type": "string"
                }
            }
        },
        "discordgo.ApplicationCommand": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "string"
                },
                "default_member_permissions": {
                    "type": "string",
                    "example": "0"
                },
                "default_permission": {
                    "description": "NOTE: DefaultPermission will be soon deprecated. Use DefaultMemberPermissions and DMPermission instead.",
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "description_localizations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "dm_permission": {
                    "type": "boolean"
                },
                "guild_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "name_localizations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "nsfw": {
                    "type": "boolean"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discordgo.ApplicationCommandOption"
                    }
                },
                "type": {
                    "$ref": "#/definitions/discordgo.ApplicationCommandType"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "discordgo.ApplicationCommandOption": {
            "type": "object",
            "properties": {
                "autocomplete": {
                    "description": "NOTE: mutually exclusive with Choices.",
                    "type": "boolean"
                },
                "channel_types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discordgo.ChannelType"
                    }
                },
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discordgo.ApplicationCommandOptionChoice"
                    }
                },
                "description": {
                    "type": "string"
                },
                "description_localizations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "max_length": {
                    "description": "Maximum length of string option.",
                    "type": "integer"
                },
                "max_value": {
                    "description": "Maximum value of number/integer option.",
                    "type": "number"
                },
                "min_length": {
                    "description": "Minimum length of string option.",
                    "type": "integer"
                },
                "min_value": {
                    "description": "Minimal value of number/integer option.",
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "name_localizations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discordgo.ApplicationCommandOption"
                    }
                },
                "required": {
                    "type": "boolean"
                },
                "type": {
                    "$ref": "#/definitions/discordgo.ApplicationCommandOptionType"
                }
            }
        },
        "discordgo.ApplicationCommandOptionChoice": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "name_localizations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "value": {}
            }
        },
        "discordgo.ApplicationCommandOptionType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11
            ],
            "x-enum-varnames": [
                "ApplicationCommandOptionSubCommand",
                "ApplicationCommandOptionSubCommandGroup",
                "ApplicationCommandOptionString",
                "ApplicationCommandOptionInteger",
                "ApplicationCommandOptionBoolean",
                "ApplicationCommandOptionUser",
                "ApplicationCommandOptionChannel",
                "ApplicationCommandOptionRole",
                "ApplicationCommandOptionMentionable",
                "ApplicationCommandOptionNumber",
                "ApplicationCommandOptionAttachment"
            ]
        },
        "discordgo.ApplicationCommandType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "ChatApplicationCommand",
                "UserApplicationCommand",
                "MessageApplicationCommand"
            ]
        },
        "discordgo.ChannelType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                10,
                11,
                12,
                13,
                15
            ],
            "x-enum-varnames": [
                "ChannelTypeGuildText",
                "ChannelTypeDM",
                "ChannelTypeGuildVoice",
                "ChannelTypeGroupDM",
                "ChannelTypeGuildCategory",
                "ChannelTypeGuildNews",
                "ChannelTypeGuildStore",
                "ChannelTypeGuildNewsThread",
                "ChannelTypeGuildPublicThread",
                "ChannelTypeGuildPrivateThread",
                "ChannelTypeGuildStageVoice",
                "ChannelTypeGuildForum"
            ]
        },
        "game.GameDelays": {
            "type": "object",
            "properties": {
                "delays": {
                    "description": "maps from origin-\u003enew phases, with the integer number of seconds for the delay",
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "game.VoiceRules": {
            "type": "object",
            "properties": {
                "deafRules": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "boolean"
                        }
                    }
                },
                "muteRules": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "premium.PremiumRecord": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "integer"
                },
                "tier": {
                    "$ref": "#/definitions/premium.Tier"
                }
            }
        },
        "premium.Tier": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "FreeTier",
                "BronzeTier",
                "SilverTier",
                "GoldTier",
                "TrialTier",
                "SelfHostTier"
            ]
        },
        "settings.GuildSettings": {
            "type": "object",
            "properties": {
                "adminIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "autoRefresh": {
                    "type": "boolean"
                },
                "delays": {
                    "$ref": "#/definitions/game.GameDelays"
                },
                "deleteGameSummary": {
                    "type": "integer"
                },
                "displayRoomCode": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "leaderboardMention": {
                    "type": "boolean"
                },
                "leaderboardMin": {
                    "type": "integer"
                },
                "leaderboardSize": {
                    "type": "integer"
                },
                "mapVersion": {
                    "type": "string"
                },
                "matchSummaryChannelID": {
                    "type": "string"
                },
                "muteSpectator": {
                    "type": "boolean"
                },
                "permissionRoleIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "unmuteDeadDuringTasks": {
                    "type": "boolean"
                },
                "voiceRules": {
                    "$ref": "#/definitions/game.VoiceRules"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "dev",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AutoMuteUs",
	Description:      "AutoMuteUs API, served independently of Discord bot shards.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
